=== cjw6k/dotfiles/utils.schema.json
{
  "$id": "https://raw.githubusercontent.com/cjw6k/dotfiles/main/dotfiles-utils.schema.json",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "dotfiles utils",
  "description": "A curated collection of useful software.",
  "type": "array",
  "items": {
    "type": "object",
    "title": "A software utility.",
    "properties": {
      "name": {"type": "string"},
      "summary": {"type": "string"},
      "uri": {
        "type": "string",
        "format": "uri"
      },
      "installs": {
        "type": "object",
        "properties": {
          "common": {"$ref": "#/$defs/InstallationSource"},
          "freebsd": {"$ref": "#/$defs/FreeBSDInstallationSource"},
          "linux": {"$ref": "#/$defs/LinuxInstallationSource"},
          "windows": {"$ref": "#/$defs/InstallationSource"}
        },
        "additionalProperties": false
      },
      "provides": {
        "type": "object",
        "properties": {
          "common": {"$ref": "#/$defs/Software"},
          "freebsd": {"$ref": "#/$defs/FreeBSDSoftware"},
          "linux": {"$ref": "#/$defs/LinuxSoftware"},
          "windows": {"$ref": "#/$defs/Software"}
        },
        "additionalProperties": false
      }
    },
    "additionalProperties": false,
    "required": [
      "name",
      "summary",
      "uri"
    ]
  },
  "minItems": 0,
  "$defs": {
    "InstallationSource": {
      "oneOf": [
        {"$ref": "#/$defs/Package"},
        {"enum": ["#na", "#custom", "#builtin", "#pip", "#psmodule"]}
      ]
    },
    "GentooInstallationSource": {
      "oneOf": [
        {"$ref": "#/$defs/GentooPackage"},
        {"enum": ["#na", "#custom", "#builtin"]}
      ]
    },
    "Package": {
      "type": "string",
      "pattern": "^[\\w\\-.]*\\w$"
    },
    "GentooPackage": {
      "type": "string",
      "pattern": "^[\\w\\-./]*\\w$"
    },
    "Software": {
      "type": "array",
      "items": {"$ref": "#/$defs/Package"},
      "minItems": 1
    },
    "FreeBSDSoftware": {
      "$ref": "#/$defs/FreeBSD",
      "properties": {},
      "additionalProperties": {"$ref": "#/$defs/Software"}
    },
    "FreeBSDInstallationSource": {
      "allOf": [
        {"$ref": "#/$defs/FreeBSD"},
        {"$ref": "#/$defs/VersionedInstallationSource"}
      ]
    },
    "LinuxInstallationSource": {
      "type": "object",
      "properties": {
        "common": {"$ref": "#/$defs/InstallationSource"},
        "alpine": {
          "allOf": [
            {"$ref": "#/$defs/Alpine"},
            {"$ref": "#/$defs/VersionedInstallationSource"}
          ]
        },
        "debian": {
          "allOf": [
            {"$ref": "#/$defs/Debian"},
            {"$ref": "#/$defs/VersionedInstallationSource"}
          ]
        },
        "gentoo": {"$ref": "#/$defs/GentooInstallationSource"},
        "ubuntu": {
          "allOf": [
            {"$ref": "#/$defs/Ubuntu"},
            {"$ref": "#/$defs/VersionedInstallationSource"}
          ]
        }
      },
      "additionalProperties": false
    },
    "LinuxSoftware": {
      "type": "object",
      "properties": {
        "common": {"$ref": "#/$defs/Software"},
        "alpine": {
          "allOf": [
            {"$ref": "#/$defs/Alpine"},
            {"$ref": "#/$defs/VersionedSoftware"}
          ]
        },
        "debian": {
          "allOf": [
            {"$ref": "#/$defs/Debian"},
            {"$ref": "#/$defs/VersionedSoftware"}
          ]
        },
        "gentoo": {"$ref": "#/$defs/Software"},
        "ubuntu": {
          "allOf": [
            {"$ref": "#/$defs/Ubuntu"},
            {"$ref": "#/$defs/VersionedSoftware"}
          ]
        }
      },
      "additionalProperties": false
    },
    "FreeBSD": {
      "type": "object",
      "properties": {
        "common": {},
        "14.0": {},
        "13.3": {},
        "13.2": {}
      },
      "additionalProperties": false
    },
    "Alpine": {
      "type": "object",
      "properties": {
        "common": {},
        "edge": {},
        "3.20": {},
        "3.19": {},
        "3.18": {},
        "3.17": {}
      },
      "additionalProperties": false
    },
    "Debian": {
      "type": "object",
      "properties": {
        "common": {},
        "sid": {},
        "trixie": {},
        "bookworm": {},
        "bullseye": {},
        "buster": {}
      },
      "additionalProperties": false
    },
    "Ubuntu": {
      "type": "object",
      "properties": {
        "common": {},
        "noble": {},
        "mantic": {},
        "lunar": {},
        "jammy": {},
        "focal": {}
      },
      "additionalProperties": false
    },
    "VersionedInstallationSource": {
      "type": "object",
      "properties": {},
      "additionalProperties": {"$ref": "#/$defs/InstallationSource"}
    },
    "VersionedSoftware": {
      "type": "object",
      "properties": {},
      "additionalProperties": {"$ref": "#/$defs/Software"}
    }
  }
}

=== cjw6k/dotfiles/home/private_dot_config/dotfiles/utils/dev/lua.json
[
  {
    "name": "lua",
    "summary": "A powerful, light-weight embeddable programming language.",
    "uri": "https://www.lua.org/",
    "provides": {"common": ["lua", "luac"]}
  },
  {
    "name": "luarocks",
    "summary": "The package manager for Lua modules.",
    "uri": "https://luarocks.org/",
    "provides": {"common": ["luarocks", "luarocks-admin"]}
  }
]

=== cjw6k/dotfiles/home/private_dot_config/dotfiles/utils/personal.json
[
  {
    "name": "1password-cli",
    "summary": "Provision secrets across development environments.",
    "uri": "https://developer.1password.com/docs/cli/",
    "installs": {
      "common": "#script",
      "freebsd": {"common": "1password-client2"},
      "linux": {"gentoo": "app-admin/op-cli-bin"}
    },
    "provides": {"common": ["op"]}
  }
]

=== cjw6k/dotfiles/home/private_dot_config/dotfiles/utils/standard.json
[
  {
    "name": "7zip",
    "summary": "A file archiver with a high compression ratio.",
    "uri": "https://www.7-zip.org/",
    "installs": {
      "freebsd": {"common": "7-zip"},
      "linux": {
        "debian": {
          "common": "7zip",
          "bullseye": "p7zip",
          "buster": "p7zip"
        },
        "gentoo": "app-arch/p7zip",
        "ubuntu": {
          "common": "7zip",
          "focal": "p7zip"
        }
      },
      "windows": "#builtin"
    },
    "provides": {
      "freebsd": {"common": ["7z"]},
      "linux": {
        "alpine": {"common": ["7z"]},
        "debian": {
          "sid": ["7z", "7za", "7zr"],
          "trixie": ["7z", "7za", "7zr"],
          "bookworm": ["7zz"],
          "bullseye": ["7zr"],
          "buster": ["7zr"]
        },
        "gentoo": ["7z", "7za", "7zr"],
        "ubuntu": {
          "noble": ["7z", "7za", "7zr"],
          "mantic": ["7zz"],
          "lunar": ["7zz"],
          "jammy": ["7zz"],
          "focal": ["7zr"]
        }
      },
      "windows": ["7z"]
    }
  },
  {
    "name": "chezmoi",
    "summary": "Manage your dotfiles across multiple diverse machines, securely.",
    "uri": "https://chezmoi.io/",
    "installs": {"common": "#builtin"}
  },
  {
    "name": "cmake",
    "summary": "An open-source, cross-platform family of tools designed to build, test and package software.",
    "uri": "https://cmake.org/",
    "installs": {
      "common": "#na",
      "linux": {"gentoo": "#custom"}
    },
    "provides": {"linux": {"gentoo": ["cmake"]}}
  },
  {
    "name": "curl",
    "summary": "A command line tool and library for transferring data with URL syntax.",
    "uri": "https://curl.se/",
    "installs": {
      "freebsd": {"common": "#builtin"},
      "linux": {"gentoo": "#builtin"},
      "windows": "#builtin"
    }
  },
  {
    "name": "delta",
    "summary": "A viewer for git and diff output.",
    "uri": "https://dandavison.github.io/delta/",
    "installs": {
      "freebsd": {"common": "git-delta"},
      "linux": {
        "debian": {
          "common": "#custom",
          "bullseye": "#na",
          "buster": "#na"
        },
        "gentoo": "dev-util/git-delta",
        "ubuntu": {
          "common": "#custom",
          "focal": "#na"
        }
      }
    },
    "provides": {
      "freebsd": {"common": ["delta"]},
      "linux": {
        "alpine": {"common": ["delta"]},
        "debian": {
          "sid": ["delta"],
          "trixie": ["delta"],
          "bookworm": ["delta"]
        },
        "gentoo": ["delta"],
        "ubuntu": {
          "noble": ["delta"],
          "mantic": ["delta"],
          "lunar": ["delta"],
          "jammy": ["delta"]
        }
      },
      "windows": ["delta"]
    }
  },
  {
    "name": "fish-shell",
    "summary": "The user-friendly command line shell.",
    "uri": "https://github.com/fish-shell/fish-shell",
    "installs": {
      "common": "fish",
      "linux": {"gentoo": "#custom"},
      "windows": "#na"
    },
    "provides": {
      "freebsd": {"common": ["fish"]},
      "linux": {"common": ["fish"]}
    }
  },
  {
    "name": "git",
    "summary": "Distributed version control system.",
    "uri": "https://git-scm.com/",
    "installs": {
      "linux": {"gentoo": "dev-vcs/git"},
      "windows": "#builtin"
    },
    "provides": {
      "common": ["git"],
      "windows": ["sh", "bash", "gitk", "git-gui", "scalar", "tig", "git-bash"]
    }
  },
  {
    "name": "jq",
    "summary": "A command-line JSON processor that uses a domain-specific language.",
    "uri": "https://stedolan.github.io/jq/",
    "installs": {
      "freebsd": {"common": "#custom"},
      "linux": {"common": "#custom"}
    }
  },
  {
    "name": "nano",
    "summary": "Command-line text editor.",
    "uri": "https://nano-editor.org/"
  },
  {
    "name": "neofetch",
    "summary": "Display information about your operating system, software and hardware.",
    "uri": "https://github.com/dylanaraps/neofetch"
  },
  {
    "name": "openssh",
    "summary": "Connectivity tool for remote login with the SSH protocol",
    "uri": "https://www.openssh.com/",
    "installs": {
      "freebsd": {"common": "#builtin"},
      "linux": {
        "debian": {"common": "openssh-server"},
        "gentoo": "#builtin",
        "ubuntu": {"common": "openssh-server"}
      },
      "windows": "#builtin"
    },
    "provides": {"common": ["ssh", "ssh-keygen"]}
  },
  {
    "name": "silver searcher, the",
    "summary": "A code-searching tool similar to ack, but faster.",
    "uri": "https://geoff.greer.fm/ag/",
    "provides": {"common": ["ag"]}
  },
  {
    "name": "starship",
    "summary": "The minimal, blazing-fast, and infinitely customizable prompt for any shell!",
    "uri": "https://starship.rs/",
    "installs": {
      "linux": {
        "debian": {"common": "#custom"},
        "ubuntu": {"common": "#custom"}
      },
      "windows": "#custom"
    }
  },
  {
    "name": "sudo",
    "summary": "Executes a single command as the superuser or another user.",
    "uri": "https://www.sudo.ws/"
  },
  {
    "name": "task",
    "summary": "A task runner / simpler Make alternative.",
    "uri": "https://taskfile.dev/",
    "installs": {
      "common": "#custom",
      "freebsd": {"common": "#custom"},
      "linux": {"alpine": {"common": "go-task"}},
      "windows": "task"
    },
    "provides": {
      "freebsd": {"common": ["task"]},
      "linux": {
        "alpine": {"common": ["go-task"]},
        "debian": {"common": ["task"]},
        "gentoo": ["task"],
        "ubuntu": {"common": ["task"]}
      },
      "windows": ["task"]
    }
  },
  {
    "name": "tealdeer",
    "summary": "Display simple help pages for command-line tools from the tldr-pages project.",
    "uri": "https://tldr.sh/",
    "provides": {"common": ["tldr"]}
  }
]

=== cjw6k/dotfiles/home/private_dot_config/dotfiles/utils/dev/elixir.json
[
  {
    "name": "elixir",
    "summary": "Elixir is a dynamic, functional language for building scalable and maintainable applications.",
    "uri": "https://github.com/elixir-lang/elixir",
    "provides": {
      "common": ["elixir"],
      "freebsd": {"common": ["mix"]},
      "linux": {"common": ["mix"]},
      "windows": ["mix.bat"]
    }
  }
]
